/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lisztian' at '2/8/18 3:08 PM' with Gradle 3.0
 *
 * @author lisztian, @date 2/8/18 3:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
